// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEZrqKIaQmyvbw5_lExdqB9-Cgb-oeck4',
    appId: '1:163079848220:web:d897878fa5e0f0c4f7bad9',
    messagingSenderId: '163079848220',
    projectId: 'food365-264fb',
    authDomain: 'food365-264fb.firebaseapp.com',
    databaseURL: 'https://food365-264fb-default-rtdb.firebaseio.com',
    storageBucket: 'food365-264fb.appspot.com',
    measurementId: 'G-9X6KDR5RN7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmAXSGi7HbKZA9zLkl8KBjXLjluEHrjtM',
    appId: '1:163079848220:android:863dcc76f962a9fef7bad9',
    messagingSenderId: '163079848220',
    projectId: 'food365-264fb',
    databaseURL: 'https://food365-264fb-default-rtdb.firebaseio.com',
    storageBucket: 'food365-264fb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBjXsSydgAWBdDDd5fWoT_JQpOUqVA1KA',
    appId: '1:163079848220:ios:7d246926a08d1cbff7bad9',
    messagingSenderId: '163079848220',
    projectId: 'food365-264fb',
    databaseURL: 'https://food365-264fb-default-rtdb.firebaseio.com',
    storageBucket: 'food365-264fb.appspot.com',
    iosClientId: '163079848220-ko3fc0rlp0ccrleanqpud346f4bh3oo6.apps.googleusercontent.com',
    iosBundleId: 'com.example.food365',
  );
}
