// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMAgclvNn3bLId7AWF-hLOMt5IudiT-Yk',
    appId: '1:76823499844:web:d1ea92b5bf1a6013ce5811',
    messagingSenderId: '76823499844',
    projectId: 'food365-ffc14',
    authDomain: 'food365-ffc14.firebaseapp.com',
    databaseURL: 'https://food365-ffc14-default-rtdb.firebaseio.com',
    storageBucket: 'food365-ffc14.appspot.com',
    measurementId: 'G-7242XGHLNM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYe6ZgESzs25O5Dz8MUbaFGMP4tuL-z-w',
    appId: '1:76823499844:android:9fa05d13db301f1ece5811',
    messagingSenderId: '76823499844',
    projectId: 'food365-ffc14',
    databaseURL: 'https://food365-ffc14-default-rtdb.firebaseio.com',
    storageBucket: 'food365-ffc14.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpAOEs2xlPP8_aqaHdtHhdkbAv-BK1XxI',
    appId: '1:76823499844:ios:f6a01972efdb6704ce5811',
    messagingSenderId: '76823499844',
    projectId: 'food365-ffc14',
    databaseURL: 'https://food365-ffc14-default-rtdb.firebaseio.com',
    storageBucket: 'food365-ffc14.appspot.com',
    iosClientId: '76823499844-15lb5n2ll0rkn9o0j31viepkh425rbi9.apps.googleusercontent.com',
    iosBundleId: 'com.example.food365',
  );
}
